### ISSUE TITLE
GB Tower on PK Stadium 1 and 2

### ISSUE THREAD

**Issue by AlexN64gamer** [sonicsnes/nrage-input-plugin#1]
PLEASE, I BEG YOU, could you try making the GB tower functional on pokemon stadium 1 and 2? I can pay for it if needed, paypal or patreon, its my childhood dream, I know there are other gb emulators, but I would like to see the doduo and dodrio tower by myself, please

**Comment by sonicsnes** [comment]
This is probably meant for project64. https://github.com/project64/project64/issues
